<?php

/**
 * @file
 * Contains nf_ontology.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nf_ontology_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dragomans module.
    case 'help.page.nf_ontology':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('nf_ontology') . '</p>';
      return $output;

    default:
  }
}
